#!/bin/bash

if [[ ! -x `which brew` ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew analytics off

brew upgrade

brew install vim
brew install tmux
brew install ctags
brew install the_silver_searcher
brew install reattach-to-user-namespace
brew install fzf

brew install fish

brew install rbenv
brew install node
brew install yarn

brew tap heroku/brew && brew install heroku

brew cleanup
