#!/bin/bash

if [[ ! -x `which brew` ]]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew analytics off

brew upgrade

brew bundle

brew cleanup
