#!/bin/bash

sudo -v

# GLOBAL CONFIGURATION

# Dark menu bar and dock 
defaults write NSGlobalDomain AppleInterfaceStyle Dark

# Fast key repeat
defaults write NSGlobalDomain KeyRepeat -int 2

# Short wait unitl key repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 12

# Disable spelling correction
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

# Enable full keyboard access with tab
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

# MENU BAR

# Show battery power in percent
defaults write com.apple.menuextra.battery ShowPercent -bool true 

# Show Bluetooth in menu bar
defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/Clock.menu"

# FINDER

# Show status bar
defaults write com.apple.finder ShowPathbar -bool true

# Show path bar
defaults write com.apple.finder ShowStatusBar -bool true

# Sort files by name
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy name" ~/Library/Preferences/com.apple.finder.plist

# Show item info on Desktop
/usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo false" ~/Library/Preferences/com.apple.finder.plist

# Show all file extensions
defaults write com.apple.finder AppleShowAllExtensions -bool true

# Show drives on Desktop
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

# DOCK

# Auto-hide 
defaults write com.apple.dock autohide -bool true

# Turn off re-arrangement of spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# SAFARI

# Turn on developer menu
defaults write com.apple.safari IncludeDevelopMenu true;

# Show status bar
defaults write com.apple.safari ShowOverlayStatusBar -bool true;

# PHOTOS

# Don't open Photos if iPhone is connected
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
