#!/bin/bash

set -e

echo Symlinking files...

DIR=$(cd $(dirname $0)/../files && pwd)

for file in $(ls $DIR); do
  SRC=$DIR/$file
  DEST=~/.$file
  echo $DEST
  ln -f -s $SRC $DEST
done

echo done.
