set nocompatible

" Load vim-plug
if empty(glob("~/.vim/autoload/plug.vim"))
  execute '!curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/plugged')
Plug 'altercation/vim-colors-solarized'
Plug 'christoomey/vim-tmux-navigator'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'derekwyatt/vim-scala'
Plug 'ervandew/supertab'
Plug 'gmarik/Vundle.vim'
Plug 'mattn/emmet-vim'
Plug 'mattn/gist-vim'
Plug 'mattn/webapi-vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'othree/yajs.vim'
Plug 'rust-lang/rust.vim'
Plug 'thoughtbot/vim-rspec'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'pangloss/vim-javascript'
Plug 'mxw/vim-jsx'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mileszs/ack.vim'
call plug#end()

filetype plugin indent on

" General
set nocompatible
set noswapfile
set nobackup
set encoding=utf-8
set listchars=tab:▸\ ,eol:¬
set anti
set hlsearch
set incsearch
set nowrap
set number
set list
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set splitbelow
set splitright
set showcmd
set wildignore+=*~,*/log/*.log,*/tmp/*,*/coverage/*.html,*/.sass-cache/*,public/system/*,public/uploads/*,*/_site/*,*/build/*,*.jpg,*.jpeg,*.gif,*.png,*.pdf,*.mp3,*/node_modules/*,*/vendor/**,*/bin/**
set belloff=all

" Solarized
syntax enable
set background=dark
colorscheme solarized

" Key mappings
let mapleader = ","
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l
nmap - :Explore<CR>
map ,, <C-^>
nmap :Vex :Vex!

" Gist
let g:gist_clip_command = 'pbcopy'
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1
let g:gist_post_private = 1

" Rspec
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
let g:rspec_command = "!bin/rspec {spec}"

" Ack
map <C-f> :Ack<Space>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Custom statusline
set statusline=\ %t\ %=%l:%c\ %y\ %m
set laststatus=2

" Enable mouse mode for resizing panes
set mouse=a

autocmd QuickFixCmdPost *grep* cwindow

" Strip whitespace on save
let strip_whitespace_on_save = 1

" Fast escape from visual mode
set timeoutlen=1000 ttimeoutlen=0

" Turn-on jsx highlighting for non-jsx files
let g:jsx_ext_required = 0

" Do not purge CTRL-P cache cross-sessions
let g:ctrlp_clear_cache_on_exit = 0
