# Configure oh-my-zsh
if [[ -a $HOME/.oh-my-zsh ]]; then
  ZSH=$HOME/.oh-my-zsh
  ZSH_THEME="alanpeabody"
  DISABLE_CORRECTION="true"
  COMPLETION_WAITING_DOTS="true"
  DISABLE_UNTRACKED_FILES_DIRTY="true"
  DISABLE_AUTO_TITLE=true

  plugins=(git)

  source $ZSH/oh-my-zsh.sh
fi

# Aliases
for file in ~/.alias_*; do
  source "$file"
done

# Path
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

# Set vim as default editor
export EDITOR='vim'

# Initialize rbenv
if [[ -x `which rbenv` ]]; then
  eval "$(rbenv init -)"
fi

# Allow [ or ] whereever you want
unsetopt nomatch

# Local configuration
if [[ -a ~/.zshrc_local ]]; then
  source ~/.zshrc_local
fi
